install.load.package <- function(x) {
 if (!require(x, character.only = TRUE))
   install.packages(x, repos='http://cran.us.r-project.org')
 require(x, character.only = TRUE)
}
package_vec <- c("automap", "doParallel", "foreach", "ncdf4", "pracma", "raster", "rgdal", "sp", "RStoolbox", "forcats")
sapply(package_vec, install.load.package)

# install.packages("automap")
# install.packages("doParallel")
# install.packages("foreach")
# install.packages("ndcf4")
# install.packages("pracma")
# install.packages("raster")
# install.packages("rgdal")
# install.packages("sp")
# install.packages("RStoolbox")
# install.packages("forcats")
# 
# library("automap")
# library("doParallel")
# library("foreach")
# library("ncdf4")
# library("pracma")
# library("raster")
# library("rgdal")
# library("sp")
# library("RStoolbox")
# library("forcats")